### ISSUE TITLE
Component's Index doesn't load

### ISSUE THREAD

**Issue by nMaroulis** [5g-empower/empower-runtime#13]
After clicking on the loaded component, the index doesn't load giving the message "The Page isn't working, 127.0.0.1 didn’t send any data. ERR_EMPTY_RESPONSE" . The logs show this message 
"""
ERROR:tornado.application:Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/usr/lib/python3.6/site-packages/tornado/httpserver.py", line 289, in finish
    self.delegate.finish()
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 2047, in finish
    self.execute()
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 2067, in execute
    **self.handler_kwargs)
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 187, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'server'
"""

**Comment by rriggio** [comment]
Which component is it? Could you report all the step you did so I can replicate the problem?

**Comment by nMaroulis** [comment]
None of the components work. The steps i did were that i created a tenant and loaded components succesfully, after clicking on the component it fails to load showing the messages that i sent you. I've tested it in two machines and it's the same. A previous version of the empower that i've been working on works fine.Could it be anything with the version of the libraries needed? Thank you for your responce

**Comment by rriggio** [comment]
Just pushed a change. Could you try again?

**Comment by nMaroulis** [comment]
Yes, thank you. Everything works fine now!
