### ISSUE TITLE
Missing template files

### ISSUE THREAD

**Issue by gmj93** [5g-empower/empower-runtime#139]
It seems that some files are missing from the repository at `empower-runtime/empower/managers/apimanager/templates`:
When running empower-runtime and trying to load 127.0.0.1:8888 gives:
```
HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3174, in wrapper
    return method(self, *args, **kwargs)
  File "/empower-runtime/empower/managers/apimanager/apimanager.py", line 133, in get
    email=account.email)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1002, in render_string
    t = loader.load(template_name)
  File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 445, in load
    self.templates[name] = self._create_template(name)
  File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 476, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/empower-runtime/empower/managers/apimanager/templates/index.html'
2019-10-16 11:48:59,083 - tornado.access - ERROR - 500 GET / (127.0.0.1) 44.71ms
```

**Comment by zulongzhang** [comment]
the latest version seems to have included the html files but there are still some htmls missing

**Comment by rriggio** [comment]
The pages of the dashboard will be include gradually in the coming days.
