### ISSUE TITLE
Empower app does not work

### ISSUE THREAD

**Issue by tomahawk291** [5g-empower/empower-runtime#24]
Hi, I try to run network app from empower-runtime/empower/apps like this
./empower-runtime.py apps.helloworld.helloworld --tenant_id=f1894546-cfe8-4f2d-910c-5c2df81ed66e

But all of them get error
ERROR:root:Error calling launch in empower.apps.helloworld.helloworld: __init__() got an unexpected keyword argument 'message'
ERROR:root:__init__() got an unexpected keyword argument 'message'
Traceback (most recent call last):
  File "/home/thang/empower-runtime/empower/main.py", line 194, in _do_launch
    RUNTIME.register_app(name, func, params)
  File "/home/thang/empower-runtime/empower/core/core.py", line 392, in register_app
    self.tenants[tenant_id].components[name] = init_method(**params)
  File "/home/thang/empower-runtime/empower/apps/helloworld/helloworld.py", line 56, in launch
    return HelloWorld(tenant_id=tenant_id, message=message, every=every)
TypeError: __init__() got an unexpected keyword argument 'message'
Traceback (most recent call last):
  File "./empower-runtime.py", line 63, in <module>
    main(ARGVS)
  File "/home/thang/empower-runtime/empower/main.py", line 309, in main
    raise RuntimeError()
RuntimeError
Any solution or i missed something? Thanks!

**Comment by rriggio** [comment]
Works for me. Do a git pull and retry.
